Add maestro retry

diff --git a/.github/workflows/eval-maestro-tests.yml b/.github/workflows/eval-maestro-tests.yml
--- a/.github/workflows/eval-maestro-tests.yml
+++ b/.github/workflows/eval-maestro-tests.yml
@@ -133,10 +133,20 @@ jobs:
         env:
           # https://github.com/facebook/react-native/blob/24e7f7d25629a7af6d877a0b79fed2faaab96437/.github/actions/maestro-ios/action.yml#L57
           MAESTRO_DRIVER_STARTUP_TIMEOUT: 1500000 # 25 min, CI can be slow at times
+          MAX_ATTEMPTS: 3 # Maestro test suits re runs in case of flakyness
         run: |
           xcrun simctl install booted ${{ matrix.app}}
 
-          maestro test ${{matrix.test_suit}} --format junit --debug-output .logs
+          # Avoid exit after command fails
+          set +e
+          # Add retries for flakyness
+          CURR_ATTEMPT=0
+          RESULT=1
+          while [[ $CURR_ATTEMPT -lt $MAX_ATTEMPTS ]] && [[ $RESULT -ne 0 ]]; do
+            maestro test ${{matrix.test_suit}} --format junit --debug-output .logs
+            RESULT=$?
+          done
+          exit $RESULT
 
       - name: Store Maestro Logs
         uses: actions/upload-artifact@v4
