chore(ci): Add required checks job for integration tests (#6018)

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -5,18 +5,6 @@ on:
       - main
 
   pull_request:
-    paths:
-      - ".github/workflows/integration-test.yml"
-      - "*.xcodeproj"
-      - "*.xcworkspace"
-      - "Samples/iOS-Cocoapods-*/**"
-      - "scripts/ci-select-xcode.sh"
-      - "scripts/ci-diagnostics.sh"
-      - "Sources/**"
-      - "*.podspec"
-      - "fastlane/**"
-      - "Gemfile.lock"
-      - "Plans/iOS-Cocoapods-Swift6_Base.xctestplan"
 
 # Concurrency configuration:
 # - We use workflow-specific concurrency groups to prevent multiple CocoaPods integration tests,
@@ -30,8 +18,24 @@ concurrency:
   cancel-in-progress: ${{ github.event_name == 'pull_request' }}
 
 jobs:
+  files-changed:
+    name: Detect File Changes
+    runs-on: ubuntu-latest
+    outputs:
+      run_integration_test_for_prs: ${{ steps.changes.outputs.run_integration_test_for_prs }}
+    steps:
+      - uses: actions/checkout@v5
+      - name: Get changed files
+        id: changes
+        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
+        with:
+          token: ${{ github.token }}
+          filters: .github/file-filters.yml
+
   test:
     name: CocoaPods Integration
+    if: github.event_name != 'pull_request' || needs.files-changed.outputs.run_integration_test_for_prs == 'true'
+    needs: files-changed
     runs-on: macos-15
     steps:
       - name: Checkout Repository
@@ -58,4 +62,26 @@ jobs:
 
       - name: Run CI Diagnostics
         if: failure()
+        shell: bash
         run: ./scripts/ci-diagnostics.sh
+
+  # This check validates that either all integration tests passed or were skipped, which allows us
+  # to make integration tests a required check with only running the integration tests when required.
+  # So, we don't have to run integration tests, for example, for Changelog or ReadMe changes.
+  integration_test-required-check:
+    needs:
+      [
+        files-changed,
+        test,
+      ]
+    name: Integration Test
+    # This is necessary since a failed/skipped dependent job would cause this job to be skipped
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+      # If any jobs we depend on fails gets cancelled or times out, this job will fail.
+      # Skipped jobs are not considered failures.
+      - name: Check for failures
+        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: |
+          echo "One of the integration test jobs has failed." && exit 1
